//
//  SRDStocksData.swift
//  Trading Companion
//
//  Created by owee on 12/05/2020.
//  Copyright © 2020 devios. All rights reserved.
//

import Foundation

let equity : Equity = Equity()

struct EquitiesGroup {
    
    let index   : String
    let list    : [String]
    
}

extension EquitiesGroup {
    
    static let SRD = EquitiesGroup(index: "^SBF120", list: [
        "AC.PA",
        "ADP.PA",
        "AI.PA",
        "AF.PA",
        "AIR.PA",
        "AKA.PA",
        "PUB.PA",
        "ALD.PA",
        "ALO.PA",
        "ATE.PA",
        "ARG.PA",
        "ATO.PA",
        "CS.PA",
        "BEN.PA",
        "BB.PA",
        "BNP.PA",
        "BOL.PA",
        "BON.PA",
        "BN.PA",
        "BVI.PA",
        "CAP.PA",
        "CARM.PA",
        "CO.PA",
        "CNP.PA",
        "COFA.PA",
        "COV.PA",
        "ACA.PA",
        "DSY.PA",
        "DBV.PA",
        "EDEN.PA",
        "EDF.PA",
        "FGR.PA",
        "ELIOR.PA",
        "ENGI.PA",
        "ERA.PA",
        "EL.PA",
        "RF.PA",
        "ERF.PA",
        "ENX.PA",
        "EO.PA",
        "FNAC.PA",
        "GFC.PA",
        "GET.PA",
        "GTT.PA",
        "ICAD.PA",
        "GLE.PAR",
        "OR.PA",
        "CA.PA",
        "MC.PA",
        "FP.PA",
        "EN.PA",
        "CGG.PA",
        "EUCAR.PA",
        "RNO.PA",
        "KN.PA",
        "ETL.PA",
        "CDI.PA",
        "FDJ.PA",
        "KER.PA",
        "VIV.PA",
        "UBI.PA",
        "DG.PA",
        "PIG.PA",
        "RMS.PA",
        "ILD.PA",
        "NK.PA",
        "IPH.PA",
        "ITP.PAR",
        "IPN.PA",
        "IPS.PA",
        "DEC.PA",
        "KER.PA",
        "LI.PA",
        "KORI.PA",
        "LHN.PA",
        "MMB.PA",
        "LR.PA",
        "MMT.PA",
        "MERY.PA",
        "ML.PA",
        "TRI.PA",
        "NEX.PA",
        "RI.PA",
        "RCO.PA",
        "RAL.PA",
        "SAVE.PA",
        "SK.PA",
        "SW.PA",
        "NOKIA.PA",
        "ORA.PA",
        "SESG.PA",
        "SOP.PA",
        "TEP.PA",
        "TFI.PA",
        "SBT.PA",
        "PVL.PA",
        "SGO.PA",
        "TFF.PA",
        "ROTH.PA",
        "SCR.PA",
        "MF.PA",
        "WLN.PA",
        "ORP.PA",
        "DIM.PA",
        "SAN.PA",
        "TNG.PA",
        "VIRP.PA",
        "RUI.PA",
        "SEV.PA",
        "FTI.PA",
        "VIE.PA",
        "UG.PA",
        "POM.PA",
        "RXL.PA",
        "SAF.PA",
        "SU.PA",
        "SPIE.PA",
        "STM.PA",
        "HO.PA",
        "FR.PA",
        "BIM.PA",
        "NXI.PA"
    ])
}
